# Import Libraries

In [39]:
import pandas as pd
import numpy as np
from ast import literal_eval
from operator import itemgetter

# Import Hasil Scoring LDA

In [40]:
data_scoring = pd.read_csv('Data Hasil Scoring Nama Barang semua NPWP 1-5 per masa pajak.csv')

# VERSION 1

## 1. Terdapat 5 topik dengan 5 skor yang berbeda-beda
## 2. Pada versi 1 ini, nilai skor LDA diambil dari nilai maximum diantara semua topik
## Asumsi : Semua Topik mengenai industri kayu dan turunannya, jika nilai semua topik ~0 maka document tidak berhubungan dengan kayu

In [65]:
data_scoring.head()

,Unnamed: 0,NPWP,score_1,score_2,score_3,score_4,score_5,score_6,score_7,score_8,score_9,score_10,score_11,score_12
0,0,505492060555,"[(2, 0.23800582), (3, 0.2030941), (4, 0.547371...","[(2, 0.1978361), (3, 0.24275233), (4, 0.5478422)]","[(0, 0.19549634), (1, 0.015388406), (2, 0.0157...","[(0, 0.56485844), (3, 0.089505784), (4, 0.3273...","[(0, 0.3331184), (3, 0.22964992), (4, 0.418798...","[(2, 0.18520235), (3, 0.2464701), (4, 0.560456)]","[(0, 0.23167455), (1, 0.010113497), (2, 0.0103...","[(0, 0.017179599), (1, 0.016669711), (2, 0.123...","[(0, 0.012814342), (1, 0.012502375), (2, 0.268...","[(0, 0.7937479), (1, 0.050003543), (2, 0.05146...","[(0, 0.31879142), (1, 0.01349862), (2, 0.01363...","[(0, 0.53792334), (1, 0.029123433), (2, 0.0293..."
1,1,513262052555,"[(0, 0.05053121), (1, 0.050025042), (2, 0.3072...",0,0,0,0,0,0,0,0,0,0,0
2,2,2100122108555,"[(0, 0.9103849), (1, 0.022224957), (2, 0.02222...",0,"[(0, 0.9264416), (1, 0.018184796), (2, 0.01818...","[(0, 0.73311096), (1, 0.066722155), (2, 0.0667...","[(0, 0.60632), (1, 0.028615221), (2, 0.1710708...","[(0, 0.05058447), (1, 0.05000592), (2, 0.05000...",0,"[(0, 0.86605716), (1, 0.03335216), (2, 0.03335...",0,0,"[(0, 0.8654074), (1, 0.033343222), (2, 0.03334...","[(0, 0.8848638), (1, 0.02858248), (2, 0.028582..."
3,3,2130386761555,0,0,0,0,0,0,"[(0, 0.0334574), (1, 0.033455368), (2, 0.53547...","[(0, 0.033362344), (1, 0.033361588), (2, 0.033...",0,0,0,0
4,4,2825102452555,0,0,0,0,0,0,0,"[(0, 0.2), (1, 0.2), (2, 0.2), (3, 0.2), (4, 0...",0,0,0,0

In [72]:
from tqdm import tqdm
NPWP = []
score_1 = []
score_2 = []
score_3 = []
score_4 = []
score_5 = []
score_6 = []
score_7 = []
score_8 = []
score_9 = []
score_10 = []
score_11 = []
score_12 = []

#for i in tqdm(range(data_scoring.shape[0])):
for i in tqdm(range(data_scoring.shape[0])):
    NPWP.append(data_scoring.NPWP.iloc[i])
    
    if data_scoring.score_1.iloc[i] == '0':
        score_1.append(0)
    else:
        hasil_1 = literal_eval(data_scoring.score_1.iloc[i])
        score_1.append(max(hasil_1,key=itemgetter(1))[1])
    
    if data_scoring.score_2.iloc[i] == '0':
        score_2.append(0)
    else:
        hasil_2 = literal_eval(data_scoring.score_2.iloc[i])
        score_2.append(max(hasil_2,key=itemgetter(1))[1])
    
    if data_scoring.score_3.iloc[i] == '0':
        score_3.append(0)
    else:
        hasil_3 = literal_eval(data_scoring.score_3.iloc[i])
        score_3.append(max(hasil_3,key=itemgetter(1))[1])
    
    if data_scoring.score_4.iloc[i] == '0':
        score_4.append(0)
    else:
        hasil_4 = literal_eval(data_scoring.score_4.iloc[i])
        score_4.append(max(hasil_4,key=itemgetter(1))[1])
    
    if data_scoring.score_5.iloc[i] == '0':
        score_5.append(0)
    else:
        hasil_5 = literal_eval(data_scoring.score_5.iloc[i])
        score_5.append(max(hasil_5,key=itemgetter(1))[1])
    
    if data_scoring.score_6.iloc[i] == '0':
        score_6.append(0)
    else:
        hasil_6 = literal_eval(data_scoring.score_6.iloc[i])
        score_6.append(max(hasil_6,key=itemgetter(1))[1])
    
    if data_scoring.score_7.iloc[i] == '0':
        score_7.append(0)
    else:
        hasil_7 = literal_eval(data_scoring.score_7.iloc[i])
        score_7.append(max(hasil_7,key=itemgetter(1))[1])
    
    if data_scoring.score_8.iloc[i] == '0':
        score_8.append(0)
    else:
        hasil_8 = literal_eval(data_scoring.score_8.iloc[i])
        score_8.append(max(hasil_8,key=itemgetter(1))[1])
    
    if data_scoring.score_9.iloc[i] == '0':
        score_9.append(0)
    else:
        hasil_9 = literal_eval(data_scoring.score_9.iloc[i])
        score_9.append(max(hasil_9,key=itemgetter(1))[1])
    
    if data_scoring.score_10.iloc[i] == '0':
        score_10.append(0)
    else:
        hasil_10 = literal_eval(data_scoring.score_10.iloc[i])
        score_10.append(max(hasil_10,key=itemgetter(1))[1])
    
    if data_scoring.score_11.iloc[i] == '0':
        score_11.append(0)
    else:
        hasil_11 = literal_eval(data_scoring.score_11.iloc[i])
        score_11.append(max(hasil_11,key=itemgetter(1))[1])
    
    if data_scoring.score_12.iloc[i] == '0':
        score_12.append(0)
    else:
        hasil_12 = literal_eval(data_scoring.score_12.iloc[i])
        score_12.append(max(hasil_12,key=itemgetter(1))[1])

pd_cust_max_scoring = pd.DataFrame()
pd_cust_max_scoring['NPWP'] = NPWP

pd_cust_max_scoring['score_1'] = score_1
pd_cust_max_scoring['score_2'] = score_2
pd_cust_max_scoring['score_3'] = score_3
pd_cust_max_scoring['score_4'] = score_4
pd_cust_max_scoring['score_5'] = score_5
pd_cust_max_scoring['score_6'] = score_6
pd_cust_max_scoring['score_7'] = score_7
pd_cust_max_scoring['score_8'] = score_8
pd_cust_max_scoring['score_9'] = score_9
pd_cust_max_scoring['score_10'] = score_10
pd_cust_max_scoring['score_11'] = score_11
pd_cust_max_scoring['score_12'] = score_12

100%|██████████████████████████████████████████████████████████████████████████| 26390/26390 [00:09<00:00, 2843.32it/s]

In [74]:
pd_cust_max_scoring.to_csv('Data_hasil_scoring_LDA_per_NPWP_max_value.csv')